server:
  port: 8888
spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customers/**, /customers, /customer-service/v3/api-docs
        - id: authentication-service
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/authentication, /authentication/**, /roles, /roles/**, /passwords, /passwords/**, /users, /users/**, /authentication-service/v3/api-docs
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: ${ALLOWED_ORIGINS:http://localhost:8081,http://localhost:8082,http://localhost:8761}
            allowedHeaders:
              - Content-Type
              - Authorization
            exposedHeaders:
              - Content-Type
              - Authorization
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
        primaryName: API Gateway Service
      - url: /customer-service/v3/api-docs
        name: Customer Service
        primaryName: Customer Service
      - url: /authentication-service/v3/api-docs
        name: Authentication Service
        primaryName: Authentication Service

eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: "*"